added base file for funding proposal
radicle-dev/radicle-grants pull request #1
Opened 2021-12-06 11:16 UTC by bordumb

## Overview
This is a PR to create the final Governance Proposal - [as outlined here](https://radicle.community/t/readme-radicle-governance-process/526) - for the Grants Program

It should follow the CLI tooling here:
https://github.com/radicle-dev/radgov

## Changes 
* Adds script for sending funding from the Radicle Treasury to the Radicle Grants Program multi-sig

2022-01-06 14:49 UTC, abbey-titcomb requested changes
@bordumb - let's just make sure the wording is all correct here before deploying.

2022-01-06 14:49 UTC, abbey-titcomb commented on governance/funding/start_funding.proposal
> +* `0x8da8f82d2bbdd896822de723f55d6edf416130ba` is the Radicle Foundation address.
```suggestion
* `0x8da8f82d2bbdd896822de723f55d6edf416130ba` is the Radicle Treasury address.
```

2022-01-06 14:49 UTC, abbey-titcomb commented on governance/funding/start_funding.proposal
> +* Snapshot Pull (94% Approval): https://snapshot.org/#/gov.radicle.eth/proposal/0xe9158c0e656918f207f76af0b05feefce2cf07c02e582944825373eebd4ddaff
```suggestion
* Snapshot Poll (94% Approval): https://snapshot.org/#/gov.radicle.eth/proposal/0xe9158c0e656918f207f76af0b05feefce2cf07c02e582944825373eebd4ddaff
```

2022-01-06 14:49 UTC, abbey-titcomb commented on governance/funding/start_funding.proposal
> +1. Transfer 1.0M USDC from the Radicle Foundation to the Radicle Grant Program's multi-sig
```suggestion
1. Transfer 1.0M USDC from the Radicle Treasury to the Radicle Grant Program's multi-sig
```

2022-01-06 14:49 UTC, abbey-titcomb commented on governance/funding/start_funding.proposal
> +2. Transfer 44,108 RAD from the Radicle Foundation to the Radicle Grant Program's multi-sig
```suggestion
2. Transfer 44,108 RAD from the Radicle Treasury to the Radicle Grant Program's multi-sig
```

2022-01-06 14:55 UTC, bordumb commented on governance/funding/start_funding.proposal
> +1. Transfer 1.0M USDC from the Radicle Foundation to the Radicle Grant Program's multi-sig
Done

2022-01-06 14:55 UTC, bordumb commented on governance/funding/start_funding.proposal
> +* Snapshot Pull (94% Approval): https://snapshot.org/#/gov.radicle.eth/proposal/0xe9158c0e656918f207f76af0b05feefce2cf07c02e582944825373eebd4ddaff
Done

2022-01-06 14:56 UTC, bordumb commented on governance/funding/start_funding.proposal
> +2. Transfer 44,108 RAD from the Radicle Foundation to the Radicle Grant Program's multi-sig
Done

2022-01-07 12:27 UTC, abbey-titcomb approved these changes

2022-01-07 12:28 UTC, merged